### ISSUE TITLE
sparql_service_url CREDENTIALS QUESTION !

### ISSUE THREAD

**Issue by espinraf** [fadirra/vizkg#10]
Hi,

I can not find how to add CREDENTIALS to the Sparql endpoint 

is it possible ?, if yes , how ?

BR,
Rafael

**Comment by espinraf** [comment]
Please check pull request

**Comment by fadirra** [comment]
Hello Rafael,

many thanks for the pull request!

We are now in the middle of testing it.

BR,
Fariz
